import json

import numpy as np
import pytest

from reimplementation.prepare_corpus import file_hash, fingerprint
from reimplementation.prepare_python_corpus import eligible, prepare_python, repository_split


def document(number, repository=None):
    return {"content": f"def function_{number}(x):\n    # " + "a useful comment " * 8 + "\n    return x + 1\n",
            "repo_name": repository or f"owner/project-{number}", "path": "module.py",
            "license": "mit", "autogenerated": False, "locator": f"shard:{number}"}


def test_python_preparation_groups_repositories_excludes_and_deduplicates(tmp_path):
    docs = [document(i) for i in range(1000)]
    excluded = {fingerprint(docs[0]["content"])}
    # The same content under a different repository must still be excluded/deduplicated.
    duplicate = {**docs[1], "repo_name": "fork/duplicate"}
    docs = [docs[0], docs[1], duplicate, {**docs[0], "repo_name": "fork/excluded"}, *docs[2:]]
    arguments = dict(encode=lambda text: [1, 2, 3, 4], eos_id=0, vocab_size=5,
                     budgets={"train": 41, "val": 13, "holdout": 17}, excluded=excluded)
    first = prepare_python(iter(docs), tmp_path / "first", **arguments)
    second = prepare_python(iter(docs), tmp_path / "second", **arguments)
    assert first == second
    assert first["statistics"]["excluded"] == 2
    assert first["statistics"]["duplicates"] == 1
    index = [json.loads(line) for line in (tmp_path / "first/documents.jsonl").read_text().splitlines()]
    assert len({row["fingerprint"] for row in index}) == len(index)
    assert not excluded & {row["fingerprint"] for row in index}
    assignments = {}
    for row in index:
        repository = row["repo_name"].casefold()
        assert assignments.setdefault(repository, row["split"]) == row["split"]
        assert row["split"] == repository_split(row["repo_name"])
        assert row["split"] == repository_split(row["repo_name"].upper())
    for split, count in arguments["budgets"].items():
        path = tmp_path / f"first/{split}.npy"
        tokens = np.fromfile(path, dtype="<u4")
        assert len(tokens) == count
        assert tokens[-1] == 0
        assert first["files"][split]["sha256"] == file_hash(path)
        assert sum(row["tokens"] for row in index if row["split"] == split) == count
    with pytest.raises(FileExistsError):
        prepare_python(iter(docs), tmp_path / "first", **arguments)


@pytest.mark.parametrize("change", [dict(content="bad python !" * 20), dict(license="gpl-3.0"),
                                    dict(autogenerated=True), dict(repo_name=""), dict(path="module.txt")])
def test_python_filters(change):
    assert not eligible({**document(1), **change})


def test_python_code_is_only_parsed(tmp_path):
    path = tmp_path / "must-not-exist"
    source = f"open({str(path)!r}, 'w').write('executed')\n# " + "comment " * 30
    assert eligible({**document(1), "content": source})
    assert not path.exists()


def test_python_incomplete_source_keeps_incomplete_manifest(tmp_path):
    with pytest.raises(ValueError, match="source exhausted"):
        prepare_python(iter([document(1)]), tmp_path / "short", encode=lambda text: [1],
                       eos_id=0, vocab_size=2, budgets=dict(train=100, val=10, holdout=10), excluded=set())
    assert json.loads((tmp_path / "short/manifest.json").read_text())["status"] == "incomplete"
