"""Prepare new Python tokens with repository-disjoint splits and explicit lineage."""

import argparse
import ast
from contextlib import ExitStack
import gzip
import hashlib
import json
from pathlib import Path

import numpy as np
import requests
from huggingface_hub import HfApi, hf_hub_url

from reimplementation.prepare_corpus import SPLITS, file_hash, fingerprint, write_manifest
from reimplementation.tokenizer import DOLMA_TOKENIZER, load_tokenizer


REPO = "codeparrot/codeparrot-clean"
REVISION = "35a59fb025bc0a102f7d96eac09d145b896d487b"
LICENSES = ("apache-2.0", "bsd-2-clause", "bsd-3-clause", "isc", "mit")


def repository_split(repository, seed=0):
    digest = hashlib.sha256(f"atelier-python-v1:{seed}:{repository.casefold()}".encode()).digest()
    bucket = int.from_bytes(digest[:8], "big") % 10_000
    return "train" if bucket < 9000 else "val" if bucket < 9500 else "holdout"


def eligible(document):
    text = document.get("content")
    if (not isinstance(text, str) or not 100 <= len(text) <= 100_000
            or not isinstance(document.get("repo_name"), str) or not document["repo_name"].strip()
            or not isinstance(document.get("path"), str) or not document["path"].endswith(".py")
            or document.get("license") not in LICENSES or document.get("autogenerated") is not False):
        return False
    try:
        ast.parse(text)  # Parse only: corpus code is never executed or imported.
    except (SyntaxError, ValueError, RecursionError):
        return False
    return True


def load_exclusions(data_dir):
    manifest_path = Path(data_dir) / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    index = Path(data_dir) / "documents.jsonl"
    if (manifest.get("status") != "complete" or manifest.get("format_version") != 1
            or manifest.get("provenance", {}).get("tokenizer") != DOLMA_TOKENIZER
            or file_hash(index) != manifest.get("document_index_sha256")):
        raise ValueError("exclusion corpus requires a complete, matching document index")
    excluded = {json.loads(line)["fingerprint"] for line in index.read_text(encoding="utf-8").splitlines()}
    return excluded, {"manifest_sha256": file_hash(manifest_path),
                      "document_index_sha256": file_hash(index), "documents": len(excluded),
                      "splits": list(SPLITS)}


def prepare_python(documents, output, *, encode, eos_id, vocab_size, budgets,
                   excluded, seed=0, provenance=None):
    if set(budgets) != set(SPLITS) or any(type(n) is not int or n < 1 for n in budgets.values()):
        raise ValueError("require positive train/val/holdout budgets")
    if not isinstance(eos_id, int) or not 0 <= eos_id < vocab_size:
        raise ValueError("EOS must be in the vocabulary")
    output = Path(output)
    output.mkdir(parents=True, exist_ok=False)
    stats = {"visited": 0, "filtered": 0, "duplicates": 0, "excluded": 0, "truncated": 0}
    totals = dict.fromkeys(SPLITS, 0)
    counts = dict.fromkeys(SPLITS, 0)
    repositories = {split: set() for split in SPLITS}
    manifest = {
        "format_version": 1, "status": "building", "provenance": provenance or {},
        "seed": seed, "token_budget": budgets, "vocab_size": vocab_size, "eos_token_id": eos_id,
        "format": "raw little-endian uint32; .npy is a legacy filename, no NumPy header",
        "split_policy": "SHA-256 of casefolded repository identity, salted with seed; 90/5/5 buckets",
        "deduplication": "NFKC + collapsed whitespace; global exact normalized text; exclude prior corpus documents",
        "limitations": "Forks and near-duplicates may cross repositories; normalized exact exclusion does not rule out partial overlap.",
        "filters": {"licenses": list(LICENSES), "min_characters": 100, "max_characters": 100_000,
                    "extension": ".py", "autogenerated": False, "python3_ast_parse": True},
        "statistics": stats, "files": {},
    }
    write_manifest(output, manifest)
    seen = set()
    try:
        with ExitStack() as stack:
            close = getattr(documents, "close", None)
            if close:
                stack.callback(close)
            streams = {split: stack.enter_context((output / f"{split}.npy").open("xb")) for split in SPLITS}
            index = stack.enter_context((output / "documents.jsonl").open("x", encoding="utf-8"))
            for document in documents:
                stats["visited"] += 1
                if stats["visited"] % 1000 == 0:
                    print(json.dumps({"visited": stats["visited"], "tokens": totals}), flush=True)
                if not eligible(document):
                    stats["filtered"] += 1
                    continue
                digest = fingerprint(document["content"])
                if digest in excluded:
                    stats["excluded"] += 1
                    continue
                if digest in seen:
                    stats["duplicates"] += 1
                    continue
                seen.add(digest)
                repository = document["repo_name"].casefold()
                split = repository_split(repository, seed)
                remaining = budgets[split] - totals[split]
                if not remaining:
                    continue
                ids = list(encode(document["content"])) + [eos_id]
                if min(ids) < 0 or max(ids) >= vocab_size:
                    raise ValueError("encoder produced a token outside the vocabulary")
                original = len(ids)
                ids = ids[:remaining]
                ids[-1] = eos_id
                np.asarray(ids, dtype="<u4").tofile(streams[split])
                index.write(json.dumps({"source": REPO, "locator": document["locator"],
                                        "repo_name": document["repo_name"], "path": document["path"],
                                        "license": document["license"], "fingerprint": digest,
                                        "content_sha256": hashlib.sha256(document["content"].encode()).hexdigest(),
                                        "split": split, "start_token": totals[split], "tokens": len(ids),
                                        "original_tokens": original, "truncated": len(ids) < original}) + "\n")
                repositories[split].add(repository)
                totals[split] += len(ids)
                counts[split] += 1
                stats["truncated"] += len(ids) < original
                if totals == budgets:
                    break
        if totals != budgets:
            raise ValueError("source exhausted before all quotas were filled")
        if any(repositories[a] & repositories[b] for a, b in
               (("train", "val"), ("train", "holdout"), ("val", "holdout"))):
            raise RuntimeError("repository leakage between splits")
        manifest["files"] = {split: {"path": f"{split}.npy", "tokens": totals[split],
                                     "documents": counts[split], "repositories": len(repositories[split]),
                                     "sha256": file_hash(output / f"{split}.npy")} for split in SPLITS}
        manifest["document_index_sha256"] = file_hash(output / "documents.jsonl")
        manifest["normalized_document_overlap"] = 0
        manifest["prior_corpus_normalized_document_overlap"] = 0
        manifest["repository_overlap"] = 0
        manifest["status"] = "complete"
        write_manifest(output, manifest)
        return manifest
    except BaseException as error:
        manifest["status"] = "incomplete"
        manifest["error_type"] = type(error).__name__
        write_manifest(output, manifest)
        raise


def stream_python():
    shards = sorted(path for path in HfApi().list_repo_files(REPO, repo_type="dataset", revision=REVISION)
                    if path.endswith(".json.gz"))
    for shard in shards:
        print(json.dumps({"streaming_shard": shard, "revision": REVISION}), flush=True)
        url = hf_hub_url(REPO, shard, repo_type="dataset", revision=REVISION)
        with requests.get(url, stream=True, timeout=(30, 300)) as response:
            response.raise_for_status()
            with gzip.GzipFile(fileobj=response.raw) as lines:
                for number, line in enumerate(lines, 1):
                    document = json.loads(line)
                    if not isinstance(document, dict):
                        document = {}
                    document["locator"] = f"{shard}:{number}"
                    yield document


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--exclude-corpus", type=Path, required=True)
    parser.add_argument("--train-tokens", type=int, default=5_000_000)
    parser.add_argument("--dev-tokens", type=int, default=250_000)
    parser.add_argument("--holdout-tokens", type=int, default=250_000)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()
    excluded, lineage = load_exclusions(args.exclude_corpus)
    tokenizer = load_tokenizer(DOLMA_TOKENIZER)
    manifest = prepare_python(
        stream_python(), args.output_dir,
        encode=lambda text: tokenizer.encode(text, add_special_tokens=False).ids,
        eos_id=tokenizer.token_to_id("<|endoftext|>"), vocab_size=tokenizer.get_vocab_size(),
        budgets={"train": args.train_tokens, "val": args.dev_tokens, "holdout": args.holdout_tokens},
        excluded=excluded, seed=args.seed,
        provenance={"dataset": {"repo_id": REPO, "revision": REVISION},
                    "tokenizer": DOLMA_TOKENIZER, "excluded_corpus": lineage},
    )
    print(json.dumps({"complete": str(args.output_dir), "files": manifest["files"]}), flush=True)


if __name__ == "__main__":
    main()
